version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - pip install awscli --upgrade
      - npm install
  build:
    commands:
      - npm test
      - npm run copy-data
      - "if [[ \"$CODEBUILD_WEBHOOK_HEAD_REF\" == \"refs/heads/staging\" ]]; then export BASE_URL=https://registry-staging.opendata.aws; else export BASE_URL=https://registry.opendata.aws; fi"
      - npm run build
      - bash _scripts/deploy.sh
